### ISSUE TITLE
error

### ISSUE THREAD

**Issue by edloomio** [Twoscope/moodle-report_completionoverview#1]
Hi  We're using your moodle plugin course completion overview plugin (2017111702) in a moodle 3.4. Unfortunatly we're getting following error when trying to access the report:

Debug info: Incorrect key file for table '/tmp/#sql_8b8_0.MYI'; try to repair it
SELECT DISTINCT cr.id AS courseid, cr.fullname AS coursename,
COUNT(DISTINCT ra.id ) AS enrols,
COUNT(DISTINCT cc.timecompleted) AS completed
FROM aca_course cr
JOIN aca_context ct ON ( ct.instanceid = cr.id )
LEFT JOIN aca_role_assignments ra ON ( ra.contextid = ct.id ) and ra.roleid = 5
LEFT JOIN aca_course_completions cc ON cc.course = cr.id
WHERE ct.contextlevel = ? AND cr.id <> ? AND cr.enablecompletion = ?
GROUP BY cr.fullname, cr.id
ORDER BY coursename
[array (
0 => '50',
1 => '1',
2 => '1',
)]
Error code: dmlreadexception
×Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 1216 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 67 of /report/completionoverview/index.php: call to mysqli_native_moodle_database->get_records_sql()

**Comment by Jim-Twoscope** [comment]
Hi There!
Thank you for choosing to use our plugin, it's really appreciated and thank you for posting the issue.
This is a bit of a strange one but I think it may be an issue with your database server rather than the plugin.

I think the  'Incorrect key file for table '/tmp/#sql_8b8_0.MYI'; try to repair it' message is normally displayed if you do not have enough space on your tmp directory on your server
It could also mean you have a corrupted table that needs to be repaired

I hope this helps!

Jim

**Comment by Jim-Twoscope** [comment]
Hi Emeta
Have you had any luck with your SQL server? Hopefully, you've found a fix and are able to use our plugin on your installation now

Jim
