### ISSUE TITLE
Moodle 3.7 website not reasponding when running report - 

### ISSUE THREAD

**Issue by Reeffaard** [Twoscope/moodle-report_completionoverview#5]
HI  - 

I installed the plugin on  Moodle 3.7 (AWS Server ) 

I seem to get a server time out error when to running the report  - server seems top freeze for 20 minutes    
Error from browser 
"The gateway did not receive a timely response from the upstream server or application."
Any Suggestions??

Thanx in advance

**Comment by Jim-Twoscope** [comment]
Hi Reeffaard

Thanks for getting in touch.

I suspect that the issue is either with the sql server having difficulty with one of the queries or the sql server not responding quickly enough or timing out too quickly.

It might be worth checking the default_socket_timeout on the sql server to see if it is set too low

The plugin has only been tested up to **Moodle 3.4** so it's possible the queries used are not optimised for Moodle 3.7. I'm afraid I haven't had time to update the plugin or check it with later versions.

Someone else suggested changing the following sql query in the plugin from:

$compdatasql = "SELECT DISTINCT cr.id AS courseid, cr.fullname AS coursename,
                COUNT(DISTINCT ra.id ) AS enrols,
                COUNT(DISTINCT cc.timecompleted) AS completed
                FROM {course} cr
                JOIN {context} ct ON ( ct.instanceid = cr.id )
                LEFT JOIN {role_assignments} ra ON ( ra.contextid = ct.id ) and ra.roleid = 5
                LEFT JOIN {course_completions} cc ON cc.course = cr.id
                WHERE ct.contextlevel = ? AND cr.id <> ? AND cr.enablecompletion = ?
               GROUP BY  cr.fullname, cr.id
               ORDER BY coursename";

To:

$compdatasql = "SELECT DISTINCT cr.id AS courseid, cr.fullname AS coursename,
                COUNT(DISTINCT ra.id ) AS enrols,
                COUNT(DISTINCT cc.timecompleted) AS completed
                FROM {course} cr
                JOIN {context} ct ON ( ct.instanceid = cr.id )
                LEFT JOIN {role_assignments} ra ON ( ra.contextid = ct.id ) and ra.roleid = 5
                LEFT JOIN {course_completions} cc ON cc.course = cr.id AND ra.userid = cc.userid
                WHERE ct.contextlevel = ? AND cr.id <> ? AND cr.enablecompletion = ?
               GROUP BY  cr.fullname, cr.id
               ORDER BY coursename";

I suspect this person was also using a Moodle version later than **3.4**

Does this help?

Jim

**Comment by Reeffaard** [comment]
Hi Jim - 

YES   
Above  Suggestion works (  Version  3.7.1+ (Build: 20190816 )

Thanks
Reeffaard

**Comment by Jim-Twoscope** [comment]
Great thank you Reeffaard

At some point I'll refactor the query and do some further testing on later Moodle versions. It's good to know that this should get the plugin working on 3.7

All the best

Jim
